/**
 * GET /api/publisher/php-receiver
 * Returns a downloadable PHP bridge file for PHP-based sites (Funerarii247, ArmeSport etc.)
 * that cannot call the Next.js API directly.
 * Protected by admin session.
 */

import { NextResponse } from 'next/server'
import { auth } from '@/auth'

function buildPhpFile(cmsUrl: string): string {
  return `<?php
/**
 * VelocityCMS Publisher Receiver Bridge
 * Generated by VelocityCMS — ${new Date().toISOString().slice(0, 10)}
 *
 * INSTALLATION
 * ============
 * 1. Upload this file to your PHP site's web root (or any protected directory).
 * 2. Set $velocitycms_url to the full URL of your VelocityCMS installation.
 * 3. Set $velocitycms_token to your site's Publisher Token (from Admin → Setări → Publisher).
 * 4. Configure your SEO Publisher to POST to: https://your-php-site.com/velocity-receiver.php
 *    with the same X-CMS-Token header.
 *
 * SECURITY NOTE
 * =============
 * This file validates the incoming X-CMS-Token before forwarding.
 * Keep $velocitycms_token secret — it is the same token configured in VelocityCMS.
 */

// ═══════════════════════════════════════════════════════════════════════════
// CONFIGURATION — Update these values
// ═══════════════════════════════════════════════════════════════════════════
$velocitycms_url   = '${cmsUrl}'; // e.g. https://cms.example.com
$velocitycms_token = 'YOUR_CMS_PUBLISHER_TOKEN'; // From Admin → Setări → Publisher

// ═══════════════════════════════════════════════════════════════════════════
// Bridge Logic — Do not modify below this line
// ═══════════════════════════════════════════════════════════════════════════

header('Content-Type: application/json');

// Accept POST only
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

// Validate incoming token
$incoming_token = isset($_SERVER['HTTP_X_CMS_TOKEN']) ? $_SERVER['HTTP_X_CMS_TOKEN'] : '';
if (empty($incoming_token) || !hash_equals($velocitycms_token, $incoming_token)) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit;
}

// Read body
$body = file_get_contents('php://input');
if (empty($body)) {
    http_response_code(400);
    echo json_encode(['error' => 'Empty request body']);
    exit;
}

// Validate JSON
json_decode($body);
if (json_last_error() !== JSON_ERROR_NONE) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON: ' . json_last_error_msg()]);
    exit;
}

// Forward to VelocityCMS
$endpoint = rtrim($velocitycms_url, '/') . '/api/publisher/receive';

$ch = curl_init($endpoint);
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST           => true,
    CURLOPT_POSTFIELDS     => $body,
    CURLOPT_HTTPHEADER     => [
        'Content-Type: application/json',
        'X-CMS-Token: ' . $velocitycms_token,
        'User-Agent: VelocityBridge/1.0',
    ],
    CURLOPT_TIMEOUT        => 30,
    CURLOPT_CONNECTTIMEOUT => 10,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_MAXREDIRS      => 3,
]);

$response = curl_exec($ch);
$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$curl_error = curl_error($ch);
curl_close($ch);

if ($curl_error) {
    http_response_code(502);
    echo json_encode(['error' => 'Failed to reach VelocityCMS: ' . $curl_error]);
    exit;
}

http_response_code($http_code ?: 500);
echo $response;
`
}

export async function GET() {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Use NEXTAUTH_URL or a sensible default for the pre-filled URL
  const cmsUrl = process.env.NEXTAUTH_URL ?? 'https://your-velocitycms-domain.com'

  const php = buildPhpFile(cmsUrl)

  return new NextResponse(php, {
    status: 200,
    headers: {
      'Content-Type': 'application/octet-stream',
      'Content-Disposition': 'attachment; filename="velocity-receiver.php"',
      'Cache-Control': 'no-store',
    },
  })
}
